title: Juan Felipe Manrique Otálora
description: Performance Marketing | Campaign Operations | Analytics | Process Improvement Curious about systems, people, and performance. I enjoy understanding complex problems and turning that understanding into meaningful action. linkedin.com/in/juan-felipe-manrique-otalora-375857234 manriqueotalora@gmail.com (+57) 317 381 1339
  
theme: jekyll-theme-minimal
show_downloads: false
